<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مگنت
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در تمرین آخر فصل «آماده‌سازی داده» قصد داریم پس از انجام چندین گام پیش‌پردازش، داده‌های آگهی‌های شغلی کوئرا را تحلیل کنیم.
آنچه در این تمرین تحلیل می‌کنیم مطمئناً بخش بسیار کوچکی از حقایق پنهان در دل داده‌هاست. پس پیشنهاد می‌کنیم علاوه بر آنچه این تمرین از شما می‌خواهد، خود نیز سعی کنید حقایق دیگری از داده‌ها استخراج کنید.
این مجموعه‌داده شامل آگهی‌های شغلی است که در کوئرا ثبت شده‌اند. برای حفظ حریم شخصی شرکت‌ها، شناسه‌ی شرکت‌های ثبت‌کننده آگهی از مجموعه‌داده حذف شده است. هر سطر از این مجموعه‌داده اطلاعات یک آگهی‌ شغلی است که شرکتی قصد جذب نیروی متناسب با آن را داشته است.
</font>
</p>

In [1]:
import pandas as pd
from datetime import datetime

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    مجموعه داده‌ی این سوال دارای ۸ ستون است که در جدول زیر به شرح ستون‌های آن پرداخته شده‌است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

| نام ستون| توضیح ستون|
|:------------------:|:------------------:|
|Level|سطح نیرویی که شرکت قصد جذب داشته. این ستون دارای ۴ مقدار منحصر به فرد است. (Junior) S (Senior)، M (Mid level)، J و (Intern) I|
|Offers Remote|نشان می‌دهد آیا شرکت امکان دورکاری برای موقعیت شغلی را فراهم کرده‌ است یا خیر.|
|Publish Time|تاریخ و ساعتی که آگهی شغلی منتشر شده است.|
|Salary|حقوقی که شرکت برای یک موقعیت شغلی خاص در نظر گرفته‌ است. <code>MT</code> آخر هر عبارت نشان‌دهنده‌ی «میلیون تومان» است. و علامت‌های <code>></code> و <code><</code> حد بالا و حد پایین حقوق نوشته‌شده را نشان می‌دهد.|
|Title|عنوانی که شرکت برای یک آگهی شغلی خاص ثبت کرده است.|
|Close Time|تاریخ و ساعتی که آگهی شغلی بسته شده است.|
|State|وضعیت فعلی آگهی شغلی را نشان می‌دهد. دارای سه مقدار منحصر به فرد است. A (Archived)، C (Closed) و PB (Published)|
|Collaboration Type|وضعیت همکاری را نشان می‌دهد که آیا FT (Full Time / تمام‌وقت) است یا PT (Part Time / پاره‌وقت)|

    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    این سوال در دو بخش تدوین شده است: پیش‌پردازش و تحلیل.
    در ابتدا مراحل پیش‌پردازش را شرح خواهیم‌ داد، سپس به سراغ مرحله‌ی تحلیل می‌رویم.
</font>
</p>

In [73]:
# TODO: read the dataset
df = pd.read_csv('job_posts.csv')
df['Publish Time'] = pd.to_datetime(df['Publish Time'])
df['Close Time'] = pd.to_datetime(df['Close Time'])
df

,Level,Offers Remote,Publish Time,Salary,Title,Close Time,State,Collaboration Type
0,S,False,2020-04-20 16:52:15,<8MT,توسعه‌دهنده Node.js,2020-06-20 03:00:06,C,FT
1,J,False,2020-02-24 12:55:02,<12MT,توسعه‌دهنده Backend,2020-04-25 03:00:05,C,FT
2,J,True,2020-02-12 13:49:32,<8MT,توسعه‌دهنده C#,2020-04-13 03:00:05,C,FT
3,J,False,2020-08-18 15:46:48,<3MT,توسعه‌دهنده Front-end,2020-08-25 21:51:39,C,PT
4,NaN,False,2017-05-01 20:23:08,NaN,توسعه دهنده #C,2017-06-30 20:23:08,C,NaN
...,...,...,...,...,...,...,...,...
7664,S,False,2021-05-17 10:11:20,NaN,DevOps Engineer,2021-06-27 04:04:50,C,FT
7665,S,False,2021-05-17 09:54:44,NaN,برنامه‌نویس ASP.NET Core,2021-06-27 04:04:50,C,FT
7666,S,False,2021-05-17 09:53:45,NaN,توسعه‌دهنده C++ (qt),2021-06-27 04:04:50,C,FT
7667,S,False,2021-05-17 08:17:06,NaN,کارشناس هوش مصنوعی,2021-06-27 04:04:50,C,FT
7668,S,True,2021-05-15 16:24:36,>12MT,توسعه‌دهنده ارشد Front-end,2021-06-27 04:04:50,C,FT

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پیش‌پردازش
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
پیش‌پردازش این سوال، شامل سه گام است که پس از اعمال آن‌ها، مجموعه‌داده‌ی ما برای تحلیل آماده می‌شود.    
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
گام اول پیش‌پردازش
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    سطرهایی که <b>هر ۳ ستون </b> <code>Level</code> ،<code>Salary</code> و <code>Collaboration Type</code> در آن‌ها گم‌شده‌اند (<code>NaN</code> هستند) را کلاً از داده‌ها حذف کنید. با داده‌ای که از این مرحله به‌دست می‌آورید سراغ گام دوم بروید.
</font>
</p>

In [74]:
# TODO: remove rows wihout "Salary", "Level" and "Collaboration Type" 
df = df.dropna(subset=['Level', 'Salary', 'Collaboration Type'], how='all')
df

,Level,Offers Remote,Publish Time,Salary,Title,Close Time,State,Collaboration Type
0,S,False,2020-04-20 16:52:15,<8MT,توسعه‌دهنده Node.js,2020-06-20 03:00:06,C,FT
1,J,False,2020-02-24 12:55:02,<12MT,توسعه‌دهنده Backend,2020-04-25 03:00:05,C,FT
2,J,True,2020-02-12 13:49:32,<8MT,توسعه‌دهنده C#,2020-04-13 03:00:05,C,FT
3,J,False,2020-08-18 15:46:48,<3MT,توسعه‌دهنده Front-end,2020-08-25 21:51:39,C,PT
5,J,False,2020-10-11 12:02:37,NaN,Associate Product Manager,2020-11-08 01:27:52,C,FT
...,...,...,...,...,...,...,...,...
7664,S,False,2021-05-17 10:11:20,NaN,DevOps Engineer,2021-06-27 04:04:50,C,FT
7665,S,False,2021-05-17 09:54:44,NaN,برنامه‌نویس ASP.NET Core,2021-06-27 04:04:50,C,FT
7666,S,False,2021-05-17 09:53:45,NaN,توسعه‌دهنده C++ (qt),2021-06-27 04:04:50,C,FT
7667,S,False,2021-05-17 08:17:06,NaN,کارشناس هوش مصنوعی,2021-06-27 04:04:50,C,FT
7668,S,True,2021-05-15 16:24:36,>12MT,توسعه‌دهنده ارشد Front-end,2021-06-27 04:04:50,C,FT

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
گام دوم پیش‌پردازش
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    مقادیر ستون <code>Salary</code> را با عددی که دارند جایگزین کنید.
    مثلا مقداری مثل 
    <code>>6MT</code>
     را به 
     <code>6</code>
      تبدیل کنید.
    یا 
    <code>>12MT</code>
     را به
      <code>12</code>
       و ... تبدیل کنید.
    <br>
    به صورت کلی، عدد هر رشته  از ستون <code>Salary</code> را جدا کرده و جایگزین همان رشته‌ی درون دیتاست کنید.
    </font>
</p>

In [75]:
# TODO: extract "Salary" values
import numpy as np
df['Salary'] = df.Salary.str.extract(r'(\d+)').astype('Float64')
df

/tmp/ipykernel_1919990/2889267974.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary'] = df.Salary.str.extract(r'(\d+)').astype('Float64')

,Level,Offers Remote,Publish Time,Salary,Title,Close Time,State,Collaboration Type
0,S,False,2020-04-20 16:52:15,8.0,توسعه‌دهنده Node.js,2020-06-20 03:00:06,C,FT
1,J,False,2020-02-24 12:55:02,12.0,توسعه‌دهنده Backend,2020-04-25 03:00:05,C,FT
2,J,True,2020-02-12 13:49:32,8.0,توسعه‌دهنده C#,2020-04-13 03:00:05,C,FT
3,J,False,2020-08-18 15:46:48,3.0,توسعه‌دهنده Front-end,2020-08-25 21:51:39,C,PT
5,J,False,2020-10-11 12:02:37,<NA>,Associate Product Manager,2020-11-08 01:27:52,C,FT
...,...,...,...,...,...,...,...,...
7664,S,False,2021-05-17 10:11:20,<NA>,DevOps Engineer,2021-06-27 04:04:50,C,FT
7665,S,False,2021-05-17 09:54:44,<NA>,برنامه‌نویس ASP.NET Core,2021-06-27 04:04:50,C,FT
7666,S,False,2021-05-17 09:53:45,<NA>,توسعه‌دهنده C++ (qt),2021-06-27 04:04:50,C,FT
7667,S,False,2021-05-17 08:17:06,<NA>,کارشناس هوش مصنوعی,2021-06-27 04:04:50,C,FT
7668,S,True,2021-05-15 16:24:36,12.0,توسعه‌دهنده ارشد Front-end,2021-06-27 04:04:50,C,FT

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
گام سوم پیش‌پردازش
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    مقادیر گم‌شده‌ی ستون <code>Salary</code> را با میانگین حقوق‌ها <b>به تفکیک سطح</b> پر کنید. یعنی اگر <code>Salary</code> یک آگهی جونیور (<code>J</code>) گم‌شده بود، آن را با میانگین همه‌ی جونیورها پر کنید؛ اگر <code>Salary</code> یک آگهی سینیور (<code>S</code>) گم‌شده بود، آن را با میانگین همه‌ی سنیورها پر کنید؛ اگر <code>Salary</code> یک آگهی میدلول (<code>M</code>) گم‌شده بود، آن را با میانگین همه‌ی میدلول‌ها پر کنید؛ اگر <code>Salary</code> یک آگهی اینترن (<code>I</code>) گم‌شده بود، آن را با میانگین همه‌ی اینترن‌ها پر کنید.
</font>
</p>

In [76]:
# TODO: fill nan values in "Salary" w.r.t. "Level"
df['Salary'] = df.groupby('Level')['Salary'].transform(lambda x: x.fillna(x.mean()))
df

/tmp/ipykernel_1919990/2832308943.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary'] = df.groupby('Level')['Salary'].transform(lambda x: x.fillna(x.mean()))

,Level,Offers Remote,Publish Time,Salary,Title,Close Time,State,Collaboration Type
0,S,False,2020-04-20 16:52:15,8.0,توسعه‌دهنده Node.js,2020-06-20 03:00:06,C,FT
1,J,False,2020-02-24 12:55:02,12.0,توسعه‌دهنده Backend,2020-04-25 03:00:05,C,FT
2,J,True,2020-02-12 13:49:32,8.0,توسعه‌دهنده C#,2020-04-13 03:00:05,C,FT
3,J,False,2020-08-18 15:46:48,3.0,توسعه‌دهنده Front-end,2020-08-25 21:51:39,C,PT
5,J,False,2020-10-11 12:02:37,5.62008,Associate Product Manager,2020-11-08 01:27:52,C,FT
...,...,...,...,...,...,...,...,...
7664,S,False,2021-05-17 10:11:20,8.790408,DevOps Engineer,2021-06-27 04:04:50,C,FT
7665,S,False,2021-05-17 09:54:44,8.790408,برنامه‌نویس ASP.NET Core,2021-06-27 04:04:50,C,FT
7666,S,False,2021-05-17 09:53:45,8.790408,توسعه‌دهنده C++ (qt),2021-06-27 04:04:50,C,FT
7667,S,False,2021-05-17 08:17:06,8.790408,کارشناس هوش مصنوعی,2021-06-27 04:04:50,C,FT
7668,S,True,2021-05-15 16:24:36,12.0,توسعه‌دهنده ارشد Front-end,2021-06-27 04:04:50,C,FT

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
حال با داده‌ای که پس از این مراحل به‌دست آورده‌اید، به حل سوالات بعدی بپردازید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
تحلیل    
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    بخش تحلیل تمرین مگنت نیز از سه گام تشکیل شده‌است:
    <ul dir=rtl>
    <li>در گام اول می‌خواهیم تاثیر کرونا بر دورکاری در ایران را بسنجیم.</li>
    <li>در سوال دوم تاثیر زمان بر انتشار آگهی‌های شغلی را اندازه می‌گیریم.</li>
    <li>و نهایتاً در گام سوم میانگین دریافتی فعالان حوزه‌ی داده را به‌دست خواهیم آورد.</li>
    </ul>
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
گام اول تحلیل
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    نرخ آگهی‌های شغلی که پیشنهاد دورکاری دارند، چقدر نسبت به قبل از اولین مورد رسمی کرونا در ایران بیشتر شده است؟ منظور از «نرخ آگهی‌های شغلی که پیشنهاد دورکاری دارند» حاصل تقسیم آگهی‌های شغلی که پیشنهاد دورکاری دارند بر تعداد کل آگهی‌هاست (تعداد ردیف‌های دیتافریم). هدف این سوال این است که بفهمیم کرونا چقدر در دورکاری موثر بوده‌ است. برای این حل سوال، نرخ آگهی‌های دورکار پیش از کرونا را از نرخ آگهی‌های دورکار پس از کرونا کم کنید (یا تعدادشان را از هم‌دیگر کم کرده و نهایتاً بر تعداد کل آگهی‌ها تقسیم کنید).
    اولین مورد رسمی کرونا در ایران را می‌توانید از متغیر <code>start_of_corona</code> که در سلول زیر گذاشته شده است پیدا کنید.
    توجه داشته باشید اولین روزی که کرونا به ایران آمد را نیز جزو روزهای <u>پس از کرونا</u> لحاظ <b>کنید</b>.
    <br>
    جواب این سوال را درون متغیر <code>remote_growth</code> ذخیره کنید. جنس این متغیر از نوع <code>float</code> است. 
    <br>
    <span color=”green”><b>راهنمایی:</b></span>
    به عنوان مثال برای محاسبه‌ی نرخ آگهی‌های پیش از کرونا باید تعداد آگهی‌هایی که هم از نوع دورکاری هستند و هم تاریخ ثبت (<code>Publish Time</code>) آن‌ها پیش از تاریخ شروع کرونا بوده است را شمارش کرده و سپس حاصل را بر تعداد کل آگهی‌ها (از هر نوعی و در هر تاریخی) تقسیم کنید.
</font>
</p>

In [77]:
start_of_corona = datetime.strptime("2020-02-19", "%Y-%m-%d")

In [78]:
# TODO: find remote_growth = ((remote offers rate after corona) - (remote offers rate before corona)) / (all offers)
rof_df = df[df['Offers Remote']]
rof_df['Publish Time'] = pd.to_datetime(rof_df['Publish Time'])
rof_after, rof_before = len(rof_df[rof_df['Publish Time'] > start_of_corona]), len(rof_df[rof_df['Publish Time'] < start_of_corona])
remote_growth = (rof_after - rof_before) / len(df)
remote_growth

/tmp/ipykernel_1919990/1743058210.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rof_df['Publish Time'] = pd.to_datetime(rof_df['Publish Time'])

0.23820038642009383

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
گام دوم تحلیل
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این گام قصد داریم به گسسته‌سازی زمان بپردازیم و باید ۲۴ ساعت شبانه‌روز را طبق جدول پایین به ۴ دسته بشکنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|اسم|بازه زمانی|
|:-------:|:-----:|
|dawn| ۰۰:۰۰ تا ۵:۵۹:۵۹|
|morning|۶:۰۰ تا ۱۱:۵۹:۵۹|
|noon|۱۲:۰۰ تا ۱۷:۵۹:۵۹|
|night|۱۸:۰۰ تا ۲۳:۵۹:۵۹|
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
 حال محاسبه کنید در هر کدام از این ۴ بازه چه تعداد آگهی شغلی منتشر شده است؟ جواب شما باید درون متغیری به اسم <code>discrete_time</code> ذخیره شده باشد. این متغیر یک دیتاسری است که نمایه‌های (<code>index</code>) آن <code>dawn</code>, <code>morning</code>, <code>noon</code> و <code>night</code> هستند و مقدار متناظر با هر کدام از این نمایه‌ها، تعداد آگهی‌های شغلی منتشرشده است. خروجی شما باید بر اساس مقادیر به صورت نزولی مرتب شده باشد.
</font>
</p>

In [99]:
# TODO: find discrete_time
discrete_time = None
from datetime import time
bins = [
    time(hour=0, minute=0, second=0),
    time(hour=5, minute=59, second=59), time(hour=11, minute=59, second=59),
    time(hour=17, minute=59, second=59), time(hour=23, minute=59, second=59)
]
labels = ['dawn', 'morning', 'noon', 'night']
temp_df = df.copy()
temp_df['Time'] = pd.cut(df['Publish Time'].dt.time, bins, labels=labels)
discrete_time = temp_df.groupby('Time')['Time'].count().sort_values(ascending=False)
discrete_time

/tmp/ipykernel_1919990/3216193229.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  discrete_time = temp_df.groupby('Time')['Time'].count().sort_values(ascending=False)

Time
noon       3950
morning    2443
night       746
dawn        107
Name: Time, dtype: int64


<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
گام سوم تحلیل
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این سوال می‌خواهیم میزان پرداختی شرکت‌ها به افراد فعال در حوزه‌ی دیتا را بررسی کنیم. برای اینکه بتوانیم آگهی‌های شغلی این حوزه را فیلتر کنیم، لیستی از کلیدواژه‌ها در سلول زیر قرار داده شده است. فرض می‌کنیم همه آگهی‌های شغلی که در عنوان (<code>Title</code>) خود یکی از این کلمات به‌کار رفته است، به حوزه‌ی داده مربوط می‌شود. لازم نیست تیتر یک آگهی تماماً یکی از کلید‌های موجود در لیست کلیدواژه‌ها باشد؛ صرفاً اگر یک کلید بخشی از تیتر یک آگهی شغلی باشد نیز ما آن آگهی شغلی را مرتبط به داده فرض می‌کنیم. مثلاً اگر کلیدی به اسم <i>Data Analyst</i> درون لیست کلیدواژه‌ها حضور داشته باشد، آنگاه یک آگهی با تیتر <i>"استخدام Data Analyst"</i> را مرتبط با حوزه‌ی داده در نظر می‌گیریم.
    <br>
    حال سوال را این‌گونه تعریف می‌کنیم: میانگین میزان پرداختی شرکت‌ها به افراد حاضر در حوزه‌ی داده به تفکیک سطح‌شان چقدر است؟ جواب خود را درون یک دیتاسری به اسم <code>data_mean</code> بریزید. نمایه‌های این سری به ترتیب حروف <code>M</code>, <code>J</code>, <code>I</code> و <code>S</code> هستند و مقدار متناظر با هر کدام از این نمایه‌ها، میانگین حقوق پرداختی شرکت‌ها به آن سطح خاص است. جنس داده این سری باید <code>float64</code> باشد    
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<span color=”green”><b>راهنمایی بزرگ:</b></span>
<font face="vazirmatn" size=3>
فراموش نکنید که پیش از انجام محاسبات، ستون <code>Title</code> را به حروف کوچک تبدیل کنید. دلیل چنین کاری این است که اگر مثلاً عنوان یک آگهی <i> Senior Data Engineer</i> باشد، کد شما باید آن را به حروف کوچک تبدیل کرده تا بتواند کلیدواژه‌ی <i>data engineer</i> را در آن پیدا کرده و آگهی را در حوزه‌ی داده تشخیص دهد.

</font>
</p>

In [94]:
keywords = ['machine learning', 'machinelearning', 'داده' , 'data scientist' ,  'datascientist' ,\
        'هوش مصنوعی' ,'پردازش ویدئو' , 'data engineer' , 'dataengineer' ,'بینایی ماشین' , 'یادگیری ماشین' ,\
        'deep learning', 'deeplearning', 'یادگیری عمیق', 'دیتاساینتیست' , 'artificial intelligence' \
        ,'artificialintelligence', 'هوش' , 'data analysis' , 'dataanalysis' , 'پردازش تصویر' , 'شبکه‌های عمیق', 'علم‌داده']

In [102]:
# TODO: find data_mean
df['Title'] = df.Title.str.lower()
data_mean = df[df.Title.str.contains(f"({'|'.join(keywords)})", regex=True)].groupby('Level')['Salary'].mean().astype(np.float64)
data_mean

/tmp/ipykernel_1919990/3983481044.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Title'] = df.Title.str.lower()
/tmp/ipykernel_1919990/3983481044.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  data_mean = df[df.Title.str.contains(f"({'|'.join(keywords)})", regex=True)].groupby('Level')['Salary'].mean().astype(np.float64)

Level
I     2.256501
J     5.750707
M    12.000000
S     8.891994
Name: Salary, dtype: float64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال‌شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [103]:
import zipfile
import joblib

pd.DataFrame.to_csv(df, 'df.csv')
joblib.dump(remote_growth, "remote_growth")
joblib.dump(discrete_time, "discrete_time")
joblib.dump(data_mean, "data_mean")

def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["df.csv", "remote_growth", "discrete_time", "data_mean", "quera_magnet.ipynb"]
compress(file_names)

File Paths:
['df.csv', 'remote_growth', 'discrete_time', 'data_mean', 'quera_magnet.ipynb']